name: Update RSS Feeds

on:
  schedule:
    # every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 feedgen dateparser

      # 4. Run your feed-update script
      - name: Generate RSS feeds
        run: python update_feeds.py

      # 5. Commit and push updated XMLs
      - name: Commit feeds
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feeds/*.xml
          git diff --staged --quiet || git commit -m "chore: update RSS feeds"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
