name: Generate RSS Feed

on:
  schedule:
    # every hour at minute 0 (UTC)
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run feed generator
        run: |
          python scripts/generate_feed.py

      - name: Commit & push updated feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feeds/forbes_articles.xml
          git diff --quiet || git commit -m "Update Forbes RSS feed"
          git push
